name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies (CI minimal)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ci.txt

      - name: Lint
        run: |
          flake8 . --ignore E203,W503,E265,W391,E302,E305,E501,F401,W292 --max-line-length 200

      - name: Run tests
        env:
          PYTHONPATH: .
        run: |
          pytest -q


